### ISSUE TITLE
Failed creating env: Invalid argument: Malformed URI: zenfs://nullb0

### ISSUE THREAD

**Issue by chiro2001** [floatious/virtual-zns-doc#1]
I'm running `db_bench` on `null_blk`, changing `DEV` to `nullb0` and running `sudo ./run_zenfs.sh`, but I got the error message `Failed creating env: Invalid argument: Malformed URI: zenfs://nullb0`.

Logs:

```
➜ chiro@chiro-pc  ~/fs/rocksdb git:(main) ✗ sudo ./run_zenfs.sh 
+ DEV=nullb0
+ FUZZ=5
++ cat /sys/class/block/nullb0/queue/chunk_sectors
+ ZONE_SZ_SECS=262144
+ ZONE_CAP=134217728
+ BASE_FZ=127506841
+ WB_SIZE=255013682
+ TARGET_FZ_BASE=255013682
+ TARGET_FILE_SIZE_MULTIPLIER=2
+ MAX_BYTES_FOR_LEVEL_BASE=510027364
+ MAX_BACKGROUND_JOBS=8
+ MAX_BACKGROUND_COMPACTIONS=8
+ OPEN_FILES=16
+ echo deadline
+ ./plugin/zenfs/util/zenfs mkfs --zbd=nullb0 --aux_path=/tmp/zenfs_nullb0 --finish_threshold=0 --force
ZenFS file system created. Free space: 7808 MB
+ ./db_bench --fs_uri=zenfs://nullb0 --key_size=16 --value_size=800 --target_file_size_base=255013682 --write_buffer_size=255013682 --max_bytes_for_level_base=510027364 --max_bytes_for_level_multiplier=4 --use_direct_io_for_flush_and_compaction --num=1500000 --benchmarks=fillrandom,overwrite --max_background_jobs=8 --max_background_compactions=8 --open_files=16
Failed creating env: Invalid argument: Malformed URI: zenfs://nullb0
```

https://github.com/floatious/virtual-zns-doc/blob/52ebdeaff752f99e534a75e7b52fbe7bdd48eb35/README.md?plain=1#L422

According to [the README.md in the zenfs repository](https://github.com/westerndigitalcorporation/zenfs#testing-with-db_bench), `fs_uri` should be `zenfs://dev:<zoned block device name>` / `zenfs://zonefs:<zonefs mountpoint>` or `zenfs://uuid:<UUID>`. I changed the line to `--fs_uri=zenfs://dev:nullb0` and it worked.

So maybe `run_zenfs.sh` needs a small fix...

**Comment by floatious** [comment]
I have updated the example accordingly:
https://github.com/floatious/virtual-zns-doc/commit/1b872cd17e11639a87b38f3f98e1f136a7941a31

Thank you!
